const rupiahDigital="Rp 100.000",baseUrl="https://zp.webinvit.id",categoryUrl=baseUrl+"/seller/api/v1/categories";let nextPageUrl=baseUrl+"/seller/api/v1/products/websites?limit=12",allThemes=[],currentFilters={acara:"all",style:"all",warna:"all",category:"all"};
const themes=document.getElementById("themes"),loadMoreBtn=document.getElementById("loadMoreBtn"),categoryFilter=document.getElementById("categoryFilter"),acaraFilter=document.getElementById("acaraFilter"),styleFilter=document.getElementById("styleFilter"),warnaFilter=document.getElementById("warnaFilter"),searchTheme=document.getElementById("searchTheme"),menuBtn=document.getElementById("menuBtn"),navLinks=document.getElementById("navLinks"),resultCount=document.getElementById("resultCount");
function waLink(product,price){return `https://wa.me/6285343556117?text=${encodeURIComponent(`Halo ZHAFRAN, saya ingin pesan ${product}. Harga: ${price}`)}`}
function normalizeItems(p){if(Array.isArray(p))return p;if(Array.isArray(p.data))return p.data;if(Array.isArray(p.products))return p.products;if(p.data&&Array.isArray(p.data.data))return p.data.data;return[]}
function getNext(p){return p?.links?.next||p?.next_page_url||p?.data?.next_page_url||null}
async function loadCategories(){try{const res=await fetch(categoryUrl),data=await res.json();normalizeItems(data).forEach(cat=>{const opt=document.createElement("option");opt.value=cat.id||cat.slug||cat.name;opt.textContent=cat.name||cat.title||"Kategori";categoryFilter.appendChild(opt)})}catch(e){console.log(e)}}
function themeImage(i){return i.thumbnail_url||i.thumbnailUrl||i.thumbnail||i.image_url||i.imageUrl||i.image||i.cover_url||i.coverUrl||i.cover||i.preview_url||i.previewUrl||i.preview||i.photo_url||i.photoUrl||i.photo||""}
function themeName(i){return i.name||i.title||"Tema Undangan Digital"}function themeCategory(i){return i.category?.name||i.category_name||i.type||"Tema Premium"}function themeCategoryId(i){return String(i.category?.id||i.category_id||i.category?.slug||i.category?.name||"all")}function detectText(i){return `${themeName(i)} ${themeCategory(i)} ${i.color||""} ${i.style||""} ${i.tags||""}`.toLowerCase()}
function renderThemes(){const kw=(searchTheme.value||"").toLowerCase().trim();const filtered=allThemes.filter(i=>{const t=detectText(i);return(!kw||t.includes(kw))&&(currentFilters.category==="all"||themeCategoryId(i)===String(currentFilters.category)||themeCategory(i)===String(currentFilters.category))&&(currentFilters.acara==="all"||t.includes(currentFilters.acara))&&(currentFilters.style==="all"||t.includes(currentFilters.style))&&(currentFilters.warna==="all"||t.includes(currentFilters.warna))});resultCount.textContent=`${filtered.length} tema tampil`;themes.innerHTML=filtered.map(i=>`<article class="theme-card reveal show"><div class="theme-img-wrap"><img src="${themeImage(i)}" alt="${themeName(i)}" loading="lazy" onerror="this.closest('.theme-img-wrap').classList.add('no-img')"></div><div class="theme-body"><span>${themeCategory(i)}</span><h3>${themeName(i)}</h3><p>Template undangan digital premium yang bisa disesuaikan dengan kebutuhan acara kamu.</p><strong>${rupiahDigital}</strong><a class="btn primary full" href="${waLink('Undangan Digital - '+themeName(i),rupiahDigital)}" target="_blank">Pesan Tema Ini</a></div></article>`).join("");if(!filtered.length)themes.innerHTML=`<div class="empty-state">Tema tidak ditemukan. Coba kata kunci atau filter lain.</div>`}
function fallbackThemes(){allThemes=[{name:"Wedding Premium Silver",category:{name:"Wedding Elegant"}},{name:"Bugis Luxury Wedding",category:{name:"Adat Bugis"}},{name:"Aqiqah Soft Gold",category:{name:"Aqiqah"}},{name:"Birthday Modern Colorful",category:{name:"Birthday"}},{name:"Khitanan Exclusive Blue",category:{name:"Khitanan"}},{name:"Engagement Luxury Minimalis",category:{name:"Engagement"}},{name:"Syukuran Green Elegant",category:{name:"Syukuran"}},{name:"Wedding Dark Premium",category:{name:"Wedding Luxury"}}];renderThemes()}
async function loadThemes(){if(!nextPageUrl){loadMoreBtn.style.display="none";return}loadMoreBtn.textContent="Memuat Tema...";try{const res=await fetch(nextPageUrl),data=await res.json(),items=normalizeItems(data);if(items.length===0&&allThemes.length===0)fallbackThemes();else{allThemes=[...allThemes,...items];nextPageUrl=getNext(data);renderThemes()}}catch(e){console.log(e);if(allThemes.length===0)fallbackThemes()}loadMoreBtn.textContent=nextPageUrl?"Tema Selengkapnya":"Semua Tema Tampil";if(!nextPageUrl)loadMoreBtn.disabled=true}
menuBtn?.addEventListener("click",()=>navLinks.classList.toggle("active"));loadMoreBtn?.addEventListener("click",loadThemes);categoryFilter?.addEventListener("change",e=>{currentFilters.category=e.target.value;renderThemes()});acaraFilter?.addEventListener("change",e=>{currentFilters.acara=e.target.value;renderThemes()});styleFilter?.addEventListener("change",e=>{currentFilters.style=e.target.value;renderThemes()});warnaFilter?.addEventListener("change",e=>{currentFilters.warna=e.target.value;renderThemes()});searchTheme?.addEventListener("input",renderThemes);loadCategories();loadThemes();